name: coriander
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  provider: ^4.1.3
  firebase_core: ^0.5.0
  cloud_firestore: ^0.14.0+2
  firebase_auth: ^0.18.0+1
  image_picker: ^0.6.7+4
  firebase_storage: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

